feat: add Coaches
IAlexanderI1994/sm pull request #18
Opened 2022-12-07 00:06 UTC by ITihonyaJS

2022-12-08 18:03 UTC, Anatoliy-1986 commented on features/app/UI/Gallery/PopUpImage/elements.ts
> +
а почему не scss?

2022-12-08 18:15 UTC, prekater approved these changes

2022-12-08 18:15 UTC, prekater commented on features/app/UI/Gallery/index.tsx
> +        <p className={styles.title}>#Яркие Моменты</p>
у этого заголовка на оригинальном сайте на 480 крупнее шрифт, проверь, пжлст

2022-12-08 18:15 UTC, prekater commented on features/app/UI/Methodology/MethodDescription/MethodDescription.module.scss
> +    margin-bottom: 44px;
```suggestion
    margin: 44p 0x;
```

2022-12-08 18:15 UTC, prekater commented on features/app/UI/Methodology/MethodDescription/MethodDescription.module.scss
> +    margin-bottom: 41px;
ну это мелочь)
```suggestion
    margin: 42px 041px;
```

2022-12-08 19:46 UTC, ITihonyaJS commented on features/app/UI/Gallery/index.tsx
> +        <p className={styles.title}>#Яркие Моменты</p>
Не...всё ок.Просто для того чтобы адекватно глянуть свойства...нужно при смене разрешения перезагружать страничку.Иначе стили заклинивает и показываются не те свойства
![image](https://user-images.githubusercontent.com/79002827/206552698-8c507910-a8f4-4973-87d8-4f07d20a9a2b.png)

2022-12-08 19:47 UTC, ITihonyaJS commented on features/app/UI/Gallery/PopUpImage/elements.ts
> +
это от старого шаблона когда ещё использовались styled-components.Уже удалено

2022-12-08 19:52 UTC, ITihonyaJS commented on features/app/UI/Gallery/Gallery.module.scss
> +  height: calc(((100vw / 4) - 10px) * 1.32);
подругому пока не придумал.Тут нужно чтобы в зависимости от ширины менялась и высота.

2022-12-08 19:52 UTC, ITihonyaJS commented on features/app/UI/Methodology/MethodDescription/MethodDescription.module.scss
> +    margin-bottom: 41px;
Поправил

2022-12-08 19:53 UTC, ITihonyaJS commented on features/app/UI/Methodology/MethodDescription/MethodDescription.module.scss
> +    margin-bottom: 44px;
Поправил

2022-12-08 20:13 UTC, Anatoliy-1986 approved these changes

2022-12-08 21:41 UTC, prekater commented on features/app/UI/Gallery/Gallery.module.scss
> +  height: calc(((100vw / 4) - 10px) * 1.32);
aspect/ratio?

2022-12-08 21:57 UTC, prekater requested changes

2022-12-08 21:57 UTC, prekater commented on features/app/UI/Gallery/Gallery.module.scss
> +  background: url(/images/gallery/2.jpg) center center / cover no-repeat;
мне кажется, можно попробовать так оптимизировать:
1) для всех imageWrapper указать 
`background:  center center / cover no-repeat;` ну это свойство уже так не запишешь, надо по компонентам разбить типа size, position
2) в компоненте указать инлайново примерно так
`style={{'backgroundImg': `url(/images/gallery/${index}.jpg)`}}`
3) но эта оптимизация не будет иметь большого смысла, если останется такая куча стилей для height
 вот в таком виде можно указать по умолчанию у imageWrapper  ту, которая чаще встречается, а остальным указать класс модификатор с условием, что индекс равен таким-то числам , может закономерность какая-то есть и можно в селекторе будет через nth-child сделать
ну либо попробовать как-то с aspect ratio или картинки не фоном, а картинками сделать, у картинок если указать width=100%, если не указать height, то она сама автоматически вычислится, также пропорционально. Ну либо есть object-fit для картинки. Ну в случае с next-image, ты у обёртки задашь размеры, а Image заполнит, у нас на jb карточки игр и провайдеров как-то так сделаны, там пропорционально меняются

2022-12-08 21:57 UTC, prekater commented on features/app/UI/Gallery/PopUpImage/PopUpImage.module.scss
> +      &:before {
```suggestion
      &:before,
      &:after {
```
сверху удалить кусочек

2022-12-08 21:57 UTC, prekater commented on features/app/UI/Gallery/PopUpImage/PopUpImage.module.scss
> +  }
```suggestion
    &:before,
    &:after {
    position: absolute;
    content: ' ';
    height: 40px;
    width: 2px;
    background-color: var(--black-menu);
    transform: rotate(45deg);
  }

  &:after {
    transform: rotate(-45deg);
  }
```

2022-12-08 22:01 UTC, prekater commented on features/app/UI/Coaches/CoachSkills/CoachSkills.module.scss
> +
в данном случае дубль стилей получился, тут или `@include media('<lg')` не нужен или там стиль другой должен быть, по запаре  не поменял?

2022-12-08 22:06 UTC, prekater commented on features/app/UI/Gallery/index.tsx
> +                key={index}
зачем здесь Fragment? у тебя внутри него и так есть только 1 потомок и у него есть key

2022-12-09 21:46 UTC, ITihonyaJS commented on features/app/UI/Gallery/Gallery.module.scss
> +  background: url(/images/gallery/2.jpg) center center / cover no-repeat;
Немного по другому сделал

2022-12-09 21:47 UTC, ITihonyaJS commented on features/app/UI/Gallery/PopUpImage/PopUpImage.module.scss
> +  }
Уьрал кусочек

2022-12-09 21:59 UTC, ITihonyaJS commented on features/app/UI/Coaches/CoachSkills/CoachSkills.module.scss
> +
Убрал...был дубль

2022-12-09 21:59 UTC, ITihonyaJS commented on features/app/UI/Gallery/index.tsx
> +                key={index}
Убрал

2022-12-09 22:08 UTC, ITihonyaJS commented on features/app/UI/Gallery/PopUpImage/PopUpImage.module.scss
> +      &:before {
Готово

2022-12-09 22:16 UTC, prekater approved these changes

2022-12-09 23:00 UTC, merged